### ISSUE TITLE
mocha fails to exit

### ISSUE THREAD

**Issue by lazylester** [mplewis/rails-vue-frontend-test-example#1]
since I'm in way over my head trying to debug this, I thought I'd mention to you the issue that mocha fails to exit when the test is complete. This is a known, intentional behaviour in Mocha 4. However it creates issues when running on (e.g.) TravisCI. If you have encountered this and have a solution that you can implement in this example app. I'd love to see it.

**Comment by HazelGrant** [comment]
I've just been attempting to implement testing for Vue in my Rails app and came across this app, and also read your issue. After struggling with the same issue you've mentioned, I found that replacing Karma with MochaWebpack makes everything easier, (mostly) prettier, and faster.

`$ yarn add mocha-webpack --dev`

Then in package.json:

```
"scripts": {
  "test": "NODE_ENV=test mocha-webpack --webpack-config config/webpack/test.js --require test/javascript/setup.js test/javascript/**/*_test.js"
}
```

The `--require test/javascript/setup.js` part provides a nice test helper file for global settings and whatnot. The last argument is where to find the tests.

Then get rid of the karma.conf.js file and run `$yarn remove karma`. I also had to use an absolute path to find the component I wanted to test (`import ComponentName from "../../app/path-to-component/component-name"` instead of just `import ComponentName from "component-name"`).

When I run `yarn test` with that setup, it runs quickly, there's nothing that fails to exit, and the test output is much more readable.

**Comment by mplewis** [comment]
Hi @lazylester,

As configured, `yarn test` starts Karma as a forever-server because it runs the following command under the hood:

```sh
NODE_ENV=test yarn karma start
```

To run Karma once, simply append `--single-run`:

```sh
yarn test --single-run
```

This appends the flag to the command being run:

```sh
NODE_ENV=test yarn karma start --single-run
```

In my projects, I typically rewrite `test` into two commands to be less ambiguous:
* `test`: run once
* `test-server`: run forever

[Here's an example](https://github.com/mplewis/memefax/blob/master/package.json#L11-L12) of similar commands in a different project of mine. Hope this helps.
